# Site settings
title: nicewoong
header-img: img/home-bg.jpg
email: thoughtscode@gmail.com
copyright_name: nicewoong_blog
description: "welcome to nicewoong blog!"
baseurl: ""
url: "http://nicewoong.github.io"
twitter_username:
github_username:  nicewoong
facebook_username:  nicewoong
email_username:  thoughtscode@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id:UA-113861447-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
